name: Echo on Src2 Directory Change

on:
  push:
    paths:
      - 'Src2/**'

jobs:
  echo-message:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Echo Message
        run: echo "Changes detected in Src2 directory"

